# Open Source Programming W9

introduction to python

# Basic Python Command

## Variables

In [1]:
print('hello world')

hello world


* **str()** -> convert a value (oftern numeric) to a **string** data type
* **int()** -> convert a value (usually float) to an **integer** data type
* **float()** -> convert a value (usually an integer) to a **float** data type

In [2]:
hotel_room = 100
tax = hotel_room * 0.08
total = hotel_room + tax
room_guests = 5
share_per_person = total/room_guests

print(share_per_person)
print("Each person needs to pay: "+str(share_per_person))

21.6
Each person needs to pay: 21.6


In [3]:
print("Each person needs to pay: "+share_per_person)

TypeError: can only concatenate str (not "float") to str

In [4]:
salutation = 'Dr.'
first_name = 'Prisha'
middle_name = 'Jai'
last_name = 'Agarwal'
suffix = 'Ph.D.'

print(salutation + ' ' + first_name + ' ' + middle_name + ' ' + last_name + ' ' + suffix)

Dr. Prisha Jai Agarwal Ph.D.


In [5]:
print('5 * 3 = ' + str(5*3))


5 * 3 = 15


## Conditionals

Comparison with numerical values
* x == y
* x != y
* x < y
* x <= y
* x > y
* x >= y

Comparison with strings
* "x" == "y" -> if words are the same, return True. Else, return false
* "x" != "y" -> if words are **not** the same, return True. Else, return false
* "x" < "y" -> if string "x" has smaller Unicode value than string "y", return True
* "x" <= "y" -> if string "x" has smaller or equal Unicode value than string "y", return True
* "x" > "y" -> if string "x" has larger Unicode value than string "y", return True
* "x" >= "y" -> if string "x" has large or equal than string "y", return True



![alt text](<download (1).png>) [alt text](W9.ipynb)

In [6]:
print("tall" < "short")

print(chr(116)+chr(97)+chr(108)+chr(108))

print('aab' < 'aac')

ord('A')

False
tall
True


65

In [7]:
# basic if-elif-else

x = 3
if x == 0:
    print('zero number')
elif x < 0:
    print('negative number')
else:
    print('positive number')

positive number


## Functions

In [8]:
def find_total_days(years, months, days):
    my_days = (years*365) + (months*30) + days
    return my_days

print(find_total_days(2,6,28))

938


In [9]:
def convert_volume(fluid_ounce):
    ml = fluid_ounce * 29.5
    # m11 = fluid_ounce * 35
    return ml

print("The volume in millimeters is " + str(convert_volume(2)))
print("The volume in millimeters is " + str(convert_volume(2)*2))

The volume in millimeters is 59.0
The volume in millimeters is 118.0


# Packages in Python

In [11]:
pip install pandas

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.0 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 819.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.2/11.5 MB 5.0 MB/s eta 0:00:03
   - -------------------------------------- 0.3/11.5 MB 4.8 MB/s eta 0:00:03
   - -------------------------------------- 0.5/11.5 MB 4.8 MB/s eta 0:00:03
   --- ------------------------------------ 0.9/11.5 MB 5.5 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.5 MB 6.7 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/11.5 MB 6.8 MB/s eta 0:00:02
   ------ --------------------------------- 1.8/11.5 MB 6.9 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.5 MB 7.1 MB/s eta 0:00:02
   --------- ------------------------------ 2.8/11.5 MB 7.4 MB/s eta 0:00:02
   --

In [12]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [13]:
pip install matplotlib

     ---------------------------------------- 0.0/162.8 kB ? eta -:--:--
     --------- --------------------------- 41.0/162.8 kB 991.0 kB/s eta 0:00:01
     ----------------------------------- -- 153.6/162.8 kB 1.8 MB/s eta 0:00:01
     -------------------------------------- 162.8/162.8 kB 1.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/7.7 MB ? eta -:--:--
   - -------------------------------------- 0.2/7.7 MB 5.0 MB/s eta 0:00:02
   -- ------------------------------------- 0.5/7.7 MB 5.1 MB/s eta 0:00:02
   ---- ----------------------------------- 0.8/7.7 MB 5.7 MB/s eta 0:00:02
   ----- ---------------------------------- 1.0/7.7 MB 6.0 MB/s eta 0:00:02
   ------- -------------------------------- 1.4/7.7 MB 6.1 MB/s eta 0:00:02
   -------- ------------------------------- 1.7/7.7 MB 6.2 MB/s eta 0:00:01
   ---------- ----------------------------- 2.0/7.7 MB 6.6 MB/s eta 0:00:01
   ------------ --------------------------- 2.3/7.7 MB 6.7 MB/s eta 0:00:01
   -------

In [14]:
pip install seaborn

   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/294.9 kB ? eta -:--:--
   --------- ----------------------------- 71.7/294.9 kB 975.2 kB/s eta 0:00:01
   ------------------------------------- -- 276.5/294.9 kB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 294.9/294.9 kB 2.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [10]:
# cara install
# pip install nama_packages

# pip install pandas
# pip install numpy
# pip install matplotlib
# pip install seaborn

SyntaxError: invalid syntax (2374496500.py, line 4)

cara manggil packages
import **nama packages** as **singkatan**

biasa packages ada singkatan nya sendiri

* numpy -> np
* pandas -> pd
* tensorflow -> tf
* matplotlib.pyplot -> plt
* seaborn -> sns

In [16]:
import pandas as pd
import numpy as np

# Numpy
https://numpy.org/doc/stable/reference/routines.html

In [17]:
x=1.34
a = [1.2,2.3,3.4,4.5,5.6]
#Rounding
print(round(x))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))
print(np.around(a))
#membuat array
b = np.array (a)
print (b)
#Sum, Product, Differences
print(sum(b))
print(np.prod(b))
print(np.diff(b))

1
1.0
2.0
1.0
[1. 2. 3. 4. 6.]
[1.2 2.3 3.4 4.5 5.6]
17.0
236.47679999999994
[1.1 1.1 1.1 1.1]


In [18]:
print(np.round(a))

[1. 2. 3. 4. 6.]


In [21]:
c = [1,2,3,4,5]
c.shape

AttributeError: 'list' object has no attribute 'shape'

In [22]:
print(b.shape)
print(b.dtype)


(5,)
float64


In [23]:
a = np.array([1,2,3,4,5,6,7,8,9,10],ndmin=2,dtype=complex)
print(a)
print(a.shape) #1 row 10 column
print(a.dtype)

[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
  10.+0.j]]
(1, 10)
complex128


In [24]:
a = np.array([[1,2,3],[4,5,6]]) #2dimenion
print (a)
a.shape #2 row 3 column
a.shape = (3,2)
print(a)
print('\n')
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #2dimention
print (c)
print(np.asmatrix(c))
print(c.shape) #4 rows 3 columns
d = np.asmatrix(c)
print(type(d))
print(type(c))
print(type(a))
c[2,1]

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
<class 'numpy.matrix'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


8

In [25]:
a = np.array([[1,2,3], [4,5,6]])
b = np.swapaxes(a,1,0)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [26]:
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #2dimention
print (d)
print(d.shape) #2 manages 2 rows 3 columns

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


# Pandas
https://pandas.pydata.org/docs/reference/index.html


In [ ]:
data = pd.read_csv('train_features_complete.csv')

data.head()

In [ ]:
df = data.copy()
df = df.drop(columns = ['highway','lit','maxspeed','name','ref'], axis = 1)
df.head()

In [ ]:
df['rerata_kecepatan'].describe()

In [ ]:
df.to_csv('df.csv', index = False)

In [ ]:
pd.read_csv('df.csv')

In [ ]:
df.to_csv('df1.csv', index = True)

In [ ]:
pd.read_csv('df1.csv')

In [ ]:
pip install openpyxl

In [ ]:
data1 = pd.read_excel('cuaca_test.xlsx')
data1.head()


In [ ]:
data2 = pd.read_excel('cuaca_train.xlsx')
data2.head()

In [ ]:
data_gabung = pd.concat([data2,data1], axis = 0)
data_gabung.head()

In [ ]:
data_gabung

In [ ]:
data_gabung.to_excel('data_gabung.xlsx', index = False)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=235be482-bea5-41e0-a131-c60cdaf79d4f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>