# Nomor 1

In [1]:
import numpy as np

def sigmoid(z):
    sigmoid = 1/(1+np.exp(-z))
    return sigmoid

z = np.random.randint(0,10,size=10)
sigmoid(z)

array([0.99908895, 0.98201379, 0.99966465, 0.99330715, 0.99987661,
       0.99330715, 0.99908895, 0.99987661, 0.99966465, 0.99987661])

# Nomor 2

In [2]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(0)

# Generate dummy data
x = np.random.randint(0, 10, size=10)
y = np.round(4 + 3 * x + np.random.randn(10), 2)

w = np.random.randn(1,1)  
b = np.zeros(1)  

x = x.reshape(10,1)
y = y.reshape(10,1)


In [3]:
x

array([[5],
       [0],
       [3],
       [3],
       [7],
       [9],
       [3],
       [5],
       [2],
       [4]])

In [4]:
y

array([[18.71],
       [ 3.87],
       [12.83],
       [11.24],
       [24.91],
       [32.37],
       [14.13],
       [18.64],
       [11.22],
       [14.66]])

In [5]:
def fits(w, b, x):
    y_hat = x @ w + b  # Perform matrix multiplication correctly
    return y_hat

y_hat = fits(w, b, x)


In [6]:
def loss_function(y_hat, y):
    m = len(y)
    loss = (1 / (2 * m)) * np.sum((y_hat - y) ** 2)
    return loss

loss_function(y_hat, y)

126.36228689239384

In [7]:
def turunan(y_hat, y, x):
    m = len(y)
    dw = (1 / m) * np.dot((y_hat - y).T, x)
    db = (1 / m) * np.sum((y_hat - y))
    return dw, db

dw, db = turunan(y_hat, y, x)

In [8]:
def update_parameter(w, b, dw, db, learning_rate=0.01):
    w = w - learning_rate * dw
    b = b - learning_rate * db
    return w, b

update_parameter(w,b,dw,db)

(array([[1.17926261]]), array([0.14501669]))

In [10]:
def regression(w, b, x, y, learning_rate=0.01, iter=1000):
    for i in range(iter):
        y_hat = fits(w, b, x)
        dw, db = turunan(y_hat, y, x)
        w, b = update_parameter(w, b, dw, db, learning_rate)
        loss = loss_function(y_hat, y)
        print(f"Iteration {i}: Loss = {loss}")
    return w, b

regression(w, b, x, y)

Iteration 0: Loss = 126.36228689239384
Iteration 1: Loss = 74.73233029958168
Iteration 2: Loss = 44.47429016160575
Iteration 3: Loss = 26.74038486482908
Iteration 4: Loss = 16.345740012096247
Iteration 5: Loss = 10.251975599068086
Iteration 6: Loss = 6.6785753636601335
Iteration 7: Loss = 4.582141761472458
Iteration 8: Loss = 3.3512350078101423
Iteration 9: Loss = 2.6275461933513604
Iteration 10: Loss = 2.201103228014482
Iteration 11: Loss = 1.9488606439291456
Iteration 12: Loss = 1.7987127042101552
Iteration 13: Loss = 1.708404782454489
Iteration 14: Loss = 1.6531752540081026
Iteration 15: Loss = 1.6185135404547983
Iteration 16: Loss = 1.5959162628622137
Iteration 17: Loss = 1.5804003119397316
Iteration 18: Loss = 1.5690454862625742
Iteration 19: Loss = 1.5601404660297342
Iteration 20: Loss = 1.5526823465119524
Iteration 21: Loss = 1.5460833604475421
Iteration 22: Loss = 1.5399990149017468
Iteration 23: Loss = 1.5342273780214726
Iteration 24: Loss = 1.5286500602262842
Iteration 25: Lo

(array([[3.12718898]]), array([3.37489423]))